In [1]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib as plt

In [8]:
maindf = pd.read_csv('AAPL_Stock_Price_Dataset_NEW.csv')
df1 = pd.read_csv('aapl_raw_data_NEW.csv')
df2 = pd.read_csv('HistoricalQuotes_NEW.csv')

In [9]:
maindf

,Date,Open,High,Low,Close,Volume,Daily_Return,Price_Range,Price_Change
0,1980-12-15,0.093684,0.093684,0.093256,0.093256,175884800,NaN,0.000428,-0.000428
1,1980-12-16,0.086839,0.086839,0.086412,0.086412,105728000,-7.339797,0.000428,-0.000428
2,1980-12-17,0.088550,0.088978,0.088550,0.088550,86441600,2.475132,0.000428,0.000000
3,1980-12-18,0.091118,0.091545,0.091118,0.091118,73449600,2.899260,0.000428,0.000000
4,1980-12-19,0.096678,0.097106,0.096678,0.096678,48630400,6.102835,0.000428,0.000000
...,...,...,...,...,...,...,...,...,...
11349,2025-12-24,272.339996,275.429993,272.200012,273.809998,17910600,0.532388,3.229980,1.470001
11350,2025-12-26,274.160004,275.369995,272.859985,273.399994,21521800,-0.149740,2.510010,-0.760010
11351,2025-12-29,272.690002,274.359985,272.350006,273.760010,23715200,0.131681,2.009979,1.070007
11352,2025-12-30,272.809998,274.079987,272.279999,273.079987,22139600,-0.248401,1.799988,0.269989
11353,2025-12-31,273.059998,273.679993,271.750000,271.859985,27293600,-0.446756,1.929993,-1.200012

In [10]:
df1

,date,open,high,low,close,volume,adjusted_close,change_percent,avg_vol_20d
0,1980-12-12,28.7392,28.8736,28.7392,28.7392,2093900,0.0992,NaN,NaN
1,1980-12-15,27.3728,27.3728,27.2608,27.2608,785200,0.0941,-5.14,NaN
2,1980-12-16,25.3792,25.3792,25.2448,25.2448,472000,0.0871,-7.44,NaN
3,1980-12-17,25.8720,26.0064,25.8720,25.8720,385900,0.0893,2.53,NaN
4,1980-12-18,26.6336,26.7456,26.6336,26.6336,327900,0.0919,2.91,NaN
...,...,...,...,...,...,...,...,...,...
10920,2024-04-09,168.7000,170.0800,168.3500,169.6700,42451200,169.6700,0.72,61247170.00
10921,2024-04-10,168.8000,169.0900,167.1100,167.7800,49709300,167.7800,-1.11,60741365.00
10922,2024-04-11,168.3400,175.4600,168.1600,175.0400,91070300,175.0400,4.33,62670445.00
10923,2024-04-12,174.2600,178.3600,174.2100,176.5500,101593300,176.5500,0.86,64104435.00
10924,2024-04-15,175.3800,176.6300,172.5000,172.6900,73096917,172.6900,-2.19,61676045.85

In [11]:
df2

            Date  Close/Last     Volume       Open       High        Low
0     02/28/2020     $273.36  106721200    $257.26    $278.41    $256.37
1     02/27/2020     $273.52   80151380     $281.1       $286    $272.96
2     02/26/2020     $292.65   49678430    $286.53    $297.88     $286.5
3     02/25/2020     $288.08   57668360    $300.95    $302.53    $286.13
4     02/24/2020     $298.18   55548830    $297.26    $304.18    $289.23
...          ...         ...        ...        ...        ...        ...
2513  03/05/2010    $31.2786  224647427   $30.7057   $31.3857   $30.6614
2514  03/04/2010    $30.1014   89591907   $29.8971   $30.1314   $29.8043
2515  03/03/2010    $29.9043   92846488   $29.8486   $29.9814   $29.7057
2516  03/02/2010    $29.8357  141486282     $29.99   $30.1186   $29.6771
2517  03/01/2010    $29.8557  137312041   $29.3928   $29.9286     $29.35

[2518 rows x 6 columns]